### ISSUE TITLE
Consider supporting xref like syntax in diagrams, translated to diagram specific syntax

### ISSUE THREAD

**Issue by djencks** [Mogztter/asciidoctor-kroki#109]
This may be mostly useful in Antora.
Many types of diagrams, in particular plantuml, support linking from svg diagram elements to elsewhere.
The idea, which Ec Roc thought of, is to allow specifying these links using xref-like syntax, and translating them into the diagram specific syntax.
Since this is kroki I propose calling them 'kref'.
I've implemented a prototype of this as a standalone project, https://gitlab.com/djencks/asciidoctor-antora-kref, but it might make sense to  integrate this into asciidoctor-kroki so the block/block macro can communicate the diagram type to the 'kref' inline macro so the desired format does not need to be further specified.
Since I don't have any idea what interpretation or translation of 'xref' syntax might be appropriate outside Antora, I've started by only registering the kref inline macro when Antora is present.

**Comment by kaja-mohideen** [comment]
Useful feature. Any update whether this proposal would make it in some future release?

**Comment by Mogztter** [comment]
I gave it a lot of thought but I think it should be done in a dedicated extension. Using a tree processor will give you the diagram type. You can also use a non-conflicting syntax (depending on the diagram syntax) to declare a cross-reference.

For instance, PlantUML is using `[[https://antora.org]]`, we could use a special protocol to indicate that this is a cross-reference: `[[antoraxref://2.3@antora:ROOT:how-antora-works.adoc]]`. The tree processor will read/parse the content and replace `antoraxref://2.3@antora:ROOT:how-antora-works.adoc` with an actual HTTP(s) URL.

**Comment by Mogztter** [comment]
Feel free to join https://chat.antora.org/ to continue the discussion.

**Comment by ggrossetie** [comment]
> can you please give a link to the discussion? We were trying to find it but with no luck.

https://antora.zulipchat.com/#narrow/stream/282400-users/topic/Integrating.20links.20to.20Antora.20objects.20in.20PlantUML.20diagrams
