### ISSUE TITLE
Local data file that is referenced relatively in Vega-Lite file is looked up relatively to the Asciidoctor file

### ISSUE THREAD

**Issue by stenzengel** [Mogztter/asciidoctor-kroki#114]
A local data file (see #53) that is referenced relatively in a Vega-Lite file is looked up relatively to the Asciidoctor file in "asciidoctor-kroki". This works differently and more logically in "asciidoctor-diagram", where the Vega-Lite file is used as origin.

### Example:
test.adoc:
```asciidoc
= Test
:kroki-fetch-diagram: true

vegalite::subdir/test.vl[]
```

subdir/test.vl:
```json
{
	"$schema": "https://vega.github.io/schema/vega-lite/v4.json",
	"data": {
		"url": "test.csv"
	},
	"encoding": {
		"x": {
			"field": "a",
			"type": "ordinal"
		},
		"y": {
			"field": "b",
			"type": "quantitative"
		}
	},
	"mark": "bar"
}
```

subdir/test.csv:
```csv
a,b
A,2.1
B,1.2
C,0.3
```

### Current behavior:
Skipping vegalite block macro. Preprocessing of Vega-Lite view specification failed, because reading the referenced local file 'test.csv' caused an error:      
Error: ENOENT: no such file or directory, open 'test.csv'

### Expected behavior:
The CSV data file should be looked up relativ to the JSON file and no error should occur.

### Workarounds:

- Put `test.csv` in the same directory as the asciidoc file
- Add relative path from asciidoc file : e.g. `"url": "subdir/test.csv"`
- Reference `test.csv` absolutely: e.g. `"url": "C:\\...\\subdir\\test.csv"`

All workarounds work with "asciidoctor-kroki" but seem to break "asciidoctor-diagram".

@Mogztter What would be the best way to fix this problem? If you have an idea, I could provide a pull request.

**Comment by Mogztter** [comment]
If you are using Node.js, then we are reading the file using:

https://github.com/Mogztter/asciidoctor-kroki/blob/01aecb3462ad12ddf0c1285003f37771141ea9dc/src/preprocess.js#L30

In your case, the code will be: `fs.readFileSync('test.csv', 'utf-8')`.
I think it's a good idea to resolve the relative path from the JSON file. We should also do the same for PlantUML. Currently, we resolve the first include from the document base directory: https://github.com/Mogztter/asciidoctor-kroki/commit/5940b9709f48c28b71853721852e34ccffec68ec

So I think we should do the following.
If we are using a block macro (i.e. `vegalite::subdir/test.vl[]`), and the target is a local URI, then we should use the base directory of the target to resolve relative paths declared in the diagram source. In this case, the target will be expanded to `/path/to/subdir/test.vl`, the base directory will be `/path/to/subdir` and, as a result, we will try to read `/path/to/subdir/test.csv`.

So you need to pass a `baseDir` argument to https://github.com/Mogztter/asciidoctor-kroki/blob/01aecb3462ad12ddf0c1285003f37771141ea9dc/src/preprocess.js#L9
