### ISSUE TITLE
Support plantuml-config-attribute for site-wide includes

### ISSUE THREAD

**Issue by gtudan** [Mogztter/asciidoctor-kroki#118]
The asciidoctor-plantuml-extension had a very cool option `plantuml-config-file` that allowed default-includes for all diagrams, so that they had the same design.

I'm aware of the plantuml-server include version, but I especially liked that the config could be checked in together with the document and that each document was able to define their own config without needing access to the server.

Could we implement such an options for Kroki?

**Comment by Mogztter** [comment]
Hello @gtudan 

Apparently, the `plantuml-config-file` attribute was used to read the file and prepend the content:

https://github.com/eshepelyuk/asciidoctor-plantuml.js/blob/eab6067d034cd09c958591ea9b1240d6d5a2f72f/src/asciidoctor-plantuml.js#L50-L56

So it should be relatively straightforward to implement. If you want to give it a try I can provide some guidance.

**Comment by gtudan** [comment]
Sure! 
I took a quick look through the code. I guess the easiest thing to do would be to add an include to the config file before passing it to the preprocessor?

**Comment by Mogztter** [comment]
@gtudan yes, just before the following line, you will need to retrieve the value of the `plantuml-config-file` attribute, read the file and prepend the content.

https://github.com/Mogztter/asciidoctor-kroki/blob/01aecb3462ad12ddf0c1285003f37771141ea9dc/src/asciidoctor-kroki.js#L72


**pseudo-code**

```js
// ...
const plantumlConfigFile = attrs['plantuml-config-file']
if (plantumlConfigFile) {
  const vfs = context.vfs
  const read = typeof vfs !== 'undefined' && typeof vfs.read === 'function' ? vfs.read : require('./node-fs.js').read
  const plantumlConfigContent = read(plantumlConfigFile, 'utf-8')
  diagramText = plantumlConfigContent + '\n' + diagramText
}
// ...
```

You can add a test in [test/test.spec.js](https://github.com/Mogztter/asciidoctor-kroki/blob/master/test/test.spec.js) and a sample PlantUML config file in the [test/fixtures](https://github.com/Mogztter/asciidoctor-kroki/tree/master/test/fixtures) directory.

**Comment by gtudan** [comment]
Thanks for the pointers, they really helped!
I used an include for the common config and let the preprocessor do the include part, which seemed easier and more flexible (i.e. it allows URLs as well).
