### ISSUE TITLE
Support workspace as base directory as configuration/fallback

### ISSUE THREAD

**Issue by myatmin** [Mogztter/asciidoctor-kroki#131]
Since Asciidoctor VSCode extension support workspace as root directory in the setting `"asciidoc.useWorkspaceRoot": true`.
It will be nice, if asciidoctor-kroki support workspace as base directory by configuration or workspace folder as fallback?

**Comment by Mogztter** [comment]
I'm not familiar with the concept of workspace root in VS code but the base directory can already be configured in Asciidoctor.js.
If this is sufficient, then you should probably open an issue in the VS code addon to properly configure the base directory when `useWorkspaceRoot` is set to true.

**Comment by Mogztter** [comment]
Closing, feel free to reopen or create an issue at https://github.com/asciidoctor/asciidoctor-vscode
