### ISSUE TITLE
How to generate Image at build time

### ISSUE THREAD

**Issue by demagnevalCegelec** [Mogztter/asciidoctor-kroki#145]
I use Asciidoctor with jruby and I'd like to have my images generated a build time instead of calling kroki web server later.
I've try to add the following atgtribute in the adoc file :
- `:kroki-default-options: inline`
- `:kroki-fetch-diagram: true`
to have the image result generate during the build and having the image either in a folder or in the resulting html, but none of them append, I still got a link to the kroki web server
What attribute should I set and how should I define them ?

**Comment by Mogztter** [comment]
This feature is currently only available in JavaScript (Node/Browser).
If you want to implement this feature in Ruby I can provide some guidance.

**Comment by Mogztter** [comment]
@demagnevalCegelec I've released [version 0.2.0](https://rubygems.org/gems/asciidoctor-kroki/versions/0.2.0) to RubyGems.org. It would be great if you could give it a try and let me know if everything is working as expected, thanks! 😉

**Comment by Mogztter** [comment]
Follow-up issue to support global options (for instance: `:kroki-default-options: inline`): https://github.com/Mogztter/asciidoctor-kroki/issues/156

**Comment by demagnevalCegelec** [comment]
I've update to asciidoctor-kroki 0.2.0 and the inline image are generated with the :kroki-fetch-diagram: true option 
It's working fine, thanks for your great work !

**Comment by Mogztter** [comment]
Thanks @demagnevalCegelec for the follow-up! I'm glad it's working for you :tada:
