### ISSUE TITLE
[Question] Shall kroki-server-url work when setting it externally?

### ISSUE THREAD

**Issue by mariotoffia** [Mogztter/asciidoctor-kroki#149]
Hi, I'm using vs code and ascidoctor plugin with the kroki-server-url set in the settings and that works just fine!

```json
{
  "asciidoc.use_kroki": true,
  "asciidoc.preview.attributes": {
    "kroki-server-url": "http://localhost:8000"
  }
}
```

I can see from the local server logs that it invokes the server locally. But when I want to use it in a Make file it seems not to accept the attribute `kroki-server-url`.

I'm doing the following:
```bash
@cd _design; node_modules/asciidoctor/bin/asciidoctor \
	-r asciidoctor-kroki \
	-r asciidoctor-highlight.js \
	-a revnumber="`git describe --tags`" \
	-a revdate="`git log -1 --format=%cd`" \
	-a revremark="`git log -1 --pretty=%B`" \
        -a kroki-server-url="http://localhost:8000" \
	go-core.adoc \
	-o ../_dist/_output/docs/go-core.html;cd -
```

Am I doing something wrong?

Cheers,
 Mario

**Comment by mariotoffia** [comment]
Hmm... need to investigate more before asking - I'm not sure that log and render correlates... caching?

**Comment by Mogztter** [comment]
For reference, I can confirm that using `-a kroki-server-url="http://localhost:8000"` should work, if it's not please reopen.
