### ISSUE TITLE
new JS-Release

### ISSUE THREAD

**Issue by gtudan** [Mogztter/asciidoctor-kroki#161]
Hi! It's been a while since the latest JS-Release (beginning ofJuly) and there have been quiet a few changes.
Could we please have a new version?

Thanks, Gregor!

**Comment by Mogztter** [comment]
Hey @gtudan,

I was planning to do a release but got sidetracked :sweat_smile: 
Indeed, there are quite a few changes! I will try to take some time this week to do the release.

Stay tuned :wink:

**Comment by Mogztter** [comment]
https://github.com/Mogztter/asciidoctor-kroki/releases/tag/v0.10.0 :tada: :tada: :tada:
