### ISSUE TITLE
Excalidraw Antora include

### ISSUE THREAD

**Issue by madmouser1** [Mogztter/asciidoctor-kroki#185]
Please advise if `excalidraw` import should work in Antora? 
Thanks

**Comment by Mogztter** [comment]
Not yet, I need to publish a new release to add `excalidraw`. Once this new version is released you will be able to include an Excalidraw diagram using either:

```
excalidraw::hello.excalidraw[svg]
```

```
[excalidraw]
....
include::hello.excalidraw[]
....
```

**Comment by madmouser1** [comment]
Many thanks @Mogztter

**Comment by Mogztter** [comment]
No worries, I will try to cut a release in the next few days :wink:
