### ISSUE TITLE
Links in svg diagrams not working using img tag

### ISSUE THREAD

**Issue by lind** [Mogztter/asciidoctor-kroki#237]
When including a svg diagram rendered by Kroki from Antora the svg diagram is included using the `<img>` tag. Eg. `<img src="_images/diag-bd61d902f74d23012f36ed92fc52a73d241631ce.svg" alt="Diagram">`
Then links in the svg is not working (not sure why).
Links in "raw" svg works fine:  [C4Model example](https://kroki.io/c4plantuml/svg/eNp9UjtvwjAQ3vMrrkxUorB06kRBDB2oUKETQpFjLokVPyL7Iui_7yU4PATtFp-_133ONJDw1BidPCkrdbNHmL-mc2cJjzSu24uEFGmE9U8gNBCvYK9E4YWB3Hn44JG3SDATtlK2iNgkWaEPzg5lE8gZ9CMY9IjttiSq3yaTWgvb-o-lMxPQylZADlZxutvBPJIHzH6HXgpcDlQiZKw3goOiEurOTOhuBkJK11gK48FzcoozzE7eaeiOLPdH7s5Ja3cIZ7vQhpIlyqp1Vf5GPuqniyMNjVD6YrB4ac8QzrIbjqw6V865VNK74HKCxVGWwhYIeE24RO-lbc6VI-ss--8H0dfkPAYQWvclSR5A3J7t-cmMIOVsF_4L9dUD3XX0HTAwjFHpTMjqCnq76hrtPsT8bVuR84mqKDPn78r_h90tsdysThKPmOceYrop0_lv-QV0Z_yN) with a link to plantuml.com

If the svg is included with `<embed>` instead then the links in svg diagram works.

It might not be the `asciidoctor-kroki` extension that add the `<img>` tag and can't change that but is there a way to get the svg links to work in a Antora site?

**Comment by Mogztter** [comment]
Hey @lind 

I think you need to add `opts=interactive`:


```
[c4plantuml,opts=interactive]
....
@startuml
!include C4_Context.puml

title System Context diagram for Internet Banking System

Person(customer, "Banking [[http://plantuml.com/ link to Plantuml]] Customer", "A customer of the bank, with personal bank accounts.")
System(banking_system, "Internet Banking System", "Allows customers to check their accounts.")

System_Ext(mail_system, "E-mail system", "The internal Microsoft Exchange e-mail system.")
System_Ext(mainframe, "Mainframe Banking System", "Stores all of the core banking information.")

Rel(customer, banking_system, "Uses")
Rel_Back(customer, mail_system, "Sends e-mails to")
Rel_Neighbor(banking_system, mail_system, "Sends e-mails", "SMTP")
Rel(banking_system, mainframe, "Uses")
@enduml
....
```

In this case, Asciidoctor will embed the SVG into a `<object>` element. This is supported in Asciidoctor.js 2.x but I don't recall if this is also supported in Antora (which is using Asciidoctor.js 1.5.x).

**Comment by lind** [comment]
Thanks @Mogztter ! 

I tried the `opts=interactive` with Antora but the result were a `<img>` tag.  I'll wait for the Asciidoctor.js version bump in Antora then.
Closing this issue.

**Comment by lind** [comment]
A short update. 

I was trying with `opts=inline` when adding this issue and that didn't work - got `<img>` tag for including the svg. Tried `opts=interactive` as you mentioned @Mogztter and that worked  - got an `<object>` instead. 
(Using Antora 2.3.4)

Thanks @Mogztter !
