### ISSUE TITLE
[Question] Slow rendering in a VS code environment

### ISSUE THREAD

**Issue by mariotoffia** [Mogztter/asciidoctor-kroki#299]
Hi, and I cannot, enough, express my gratitude for this excellent project - thanks!!! 😊

I've done a diagram and have it included in a single document with almost no text. It takes a rather fair mount of time to render - I can appreciate that - but after rendering it caches an _SVG_ file say _"diag-69fa87b81a8549bdafb85dee975c2a5b6aa72114.svg"_ and uses that for rendering the preview.

However, the vs code gets almost unresponsive - much like it still tries to re-render it every time it is saved? Is this the correct behaviour - is it the asciidoc-vscode  I should contact instead of you? 

What I thought it would do is to make the initial preview take a fair amount of time, but then it will not need any additional time unless the underlying device-connect.json modification (or maybe size) has changed? Hance is responsive. If I comment out the _excalidraw_ block it gets responsive again.

I include the file using
```asciidoc
ifndef::kroki-http-method[:kroki-http-method: post]
ifndef::kroki-fetch-diagram[:kroki-fetch-diagram: true]
ifndef::kroki-default-format[:kroki-default-format: svg]
ifndef::kroki-server-url[:kroki-server-url: http://localhost:8000]

[excalidraw]
----
include::../../figures/device-connect.json[options=inline]
----
```

I've attached the excalidraw drawing _device-connect.json_.

Oh forgot to mention that I use the vs code and the [asciidoctor-vscode](https://github.com/asciidoctor/asciidoctor-vscode) plugin (v2.8.9 - i.e. latest). Also that I run the latest Kroki docker images. I run under Windows/WSL2.

Cheers,
 Mario :)

[device-connect.zip - contains excalidraw json file](https://github.com/Mogztter/asciidoctor-kroki/files/7242437/device-connect.zip)

**Comment by Mogztter** [comment]
If the file already exists on disk (same content) it should read the file from the local disk and not call the server:

https://github.com/Mogztter/asciidoctor-kroki/blob/369af7f050e456033779ca10e266e7fb2d62f309/src/fetch.js#L46

The Kroki extension will run every time `asciidoctor.convert` is called but if the file already exists it should be relatively fast.
You can try to debug the VS code to find the root cause.

At this point, I cannot tell if this is an integration issue with the VS code extension or if something is wrong in the Kroki extension.

**Comment by mariotoffia** [comment]
Hi @Mogztter and thanks for your prompt answer!

I've done a generate step to manually generate those excalidraw drawings and included the SVG instead to avoid this. 

I'm guessing this would be hard to diagnose.

in my _Makefile_
```bash
generate:
	@mkdir -p assets/autogen
	@cat figures/device-connect.json | curl  -X POST --data-binary @- http://localhost:8000/excalidraw/svg > assets/autogen/device-connect.svg 
```

Again, thanks!!!
 Mario :)
