### ISSUE TITLE
Fix how to soft set a kroki attribute in Antora (use a trailing @ on the value, not the attribute)

### ISSUE THREAD

**Issue by sturtison** [Mogztter/asciidoctor-kroki#308]
Hi @Mogztter while reading the README.md, following and using the guide, it seems that the info below is perhaps out of date.

https://github.com/Mogztter/asciidoctor-kroki/blob/0cfab7d60eeccb6bf64b17928156054ea6c799a9/README.md?plain=1#L361-L367

The [antora docs for soft set](https://docs.antora.org/antora/2.3/component-attributes/#soft-set) describe that the @ should trail the value, not the attribute.

The actual result is line should hold ```kroki-default-format: png@```

I'm raising a PR from my fork using this issue number if it's suitable for you to accept.

/edits: Format result line.

**Comment by Mogztter** [comment]
fixed in #309
