### ISSUE TITLE
OS-specific "kroki-plantuml-include-paths" directory-delimiter inhibits cross-platform collaboration

### ISSUE THREAD

**Issue by thepartisan** [Mogztter/asciidoctor-kroki#346]
The current behavior of the setting "kroki-plantuml-include-paths" is to have one string to define multiple include paths separated by ";" on Windows and ":" on nix-OSes (see [documentation](https://github.com/Mogztter/asciidoctor-kroki#configuration) ). This inhibits sharing one workspace settings.json between people that use different OSes.

A non-backwards-compatibility-breaking fix could be to additionally allow "," as separator.

**Comment by Mogztter** [comment]
> A non-backwards-compatibility-breaking fix could be to additionally allow "," as separator.

One issue is that `,` is a valid character on Unix: `foo,`.

> This inhibits sharing one workspace settings.json between people that use different OSes.

That would be beneficial, could you please share an example of such configuration? Are you using absolute paths? Are you using a shared drive?

**Comment by Mogztter** [comment]
Closing.
If you are still interested please join https://kroki.zulipchat.com/ so we can discuss the best approach.
