### ISSUE TITLE
outdated kroki server

### ISSUE THREAD

**Issue by ferrao** [Mogztter/asciidoctor-kroki#364]
I am having issues rendering mermaid diagrams with kroki, but they render just fine using `mermaid` or `asciidoctor-diagram`.
Not sure what is the version of mermaid that is running on `kroki.io`, but I suspect it might be outdated.

Looking at [kroki](https://github.com/yuzutech/kroki) it seems to have the latest mermaid version (`8.14.0`).
Any chance you can update on your side?

**Comment by Mogztter** [comment]
This extension does rely on https://kroki.io or on a local server.
Could you please provide a reproduction case?

**Comment by ferrao** [comment]
> This extension does rely on https://kroki.io or on a local server.

But is it using [your fork](https://github.com/Mogztter/kroki) ? If so, it is outdated and using mermaid `8.5.0`.
My diagrams render ok in the latest `8.14.0`

> Could you please provide a reproduction case? 

Yes, let me try to get something that fails to you.

**Comment by ferrao** [comment]
@Mogztter while trying to get a minimal example for you I found the problem.

When using `note` and the `<>` chars, we need to escape them as html entities `&lt;` and `&gt;`

But for some reasons, mermaid `8.14.0` does not need that.

**Comment by Mogztter** [comment]
> But is it using [your fork](https://github.com/Mogztter/kroki) ? If so, it is outdated and using mermaid 8.5.0.
My diagrams render ok in the latest 8.14.0

No, this extension is using the version deployed on https://kroki.io/

> When using note and the <> chars, we need to escape them as html entities &lt; and &gt;
But for some reason, mermaid 8.14.0 does not need that.

Could you please provide a minimal example?

**Comment by ferrao** [comment]
> Could you please provide a minimal example?

```
sequenceDiagram
    rect rgba(200, 150, 255, 0.2)
    participant John
    Note over John: Text in <<note>>
    end
```
With the mermaid cli this diagram renders as:

`$ mmdc -i example.mmdc -o example.svg`
![example](https://user-images.githubusercontent.com/418243/164432075-cd73bf1d-621f-46aa-bf87-9d21b99f0cb7.svg)

But in [Kroki.io](https://kroki.io/) it renders as:

![2022-04-21-110658_1115x267_escrotum](https://user-images.githubusercontent.com/418243/164432319-e49ab5c1-1504-4120-b5b1-6dc4b24486d9.png)

If you replace `<>` with the respective html entities it renders ok:

![2022-04-21-110841_967x395_escrotum](https://user-images.githubusercontent.com/418243/164432565-1c74ad13-3d16-4f11-9194-706abcd83266.png)

**Comment by Mogztter** [comment]
Thanks for providing a minimal reproduction case. I believe this is a bug in yuzutech/kroki.
I cannot move this issue, so I've created a new one: https://github.com/yuzutech/kroki/issues/1253
