### ISSUE TITLE
Document how to use with Antora

### ISSUE THREAD

**Issue by marcelstoer** [Mogztter/asciidoctor-kroki#37]
This looks like a real gem 💎 !

But how do you use it with Antora? I installed Antora with `npm` and have been happily running `antora antora-playbook.yml` so far. What do I need to change to have something simple as 

```
[plantuml,alice-bob,svg,role=sequence]
....
alice -> bob
....
```

inside an `.adoc` rendered as a diagram?

**Comment by Mogztter** [comment]
Hello @marcelstoer 

Thanks for your interest! And yes we need to add a section in the README...

I believe that the setup is relatively straightforward:

1. Install the extension in your playbook project:

```
npm i asciidoctor-kroki
```

2. Configure your playbook to enable the extension:

```yml
asciidoc:
  extensions:
  - asciidoctor-kroki
```

@akosma could probably help you get started.
Did I forgot something in my installation procedure?

**Comment by marcelstoer** [comment]
I'm inclined to close this as resolved. Thank you so much!

But...since there is no other way of asking (that I'm aware of) allow a follow-up question. I know I can use kroki.io or run my own Kroki. Is there a middle ground? Could the kroki.io images be downloaded into a local assets folder so we're only dependent on kroki.io at (documentation-)build time?

**Comment by Mogztter** [comment]
> I'm inclined to close this as resolved. Thank you so much!

Do you confirm that the above procedure is working?
But please let this issue open, we need to document it.

> But...since there is no other way of asking (that I'm aware of) allow a follow-up question.

We do have a Gitter channel for discussion: https://gitter.im/kroki-project/community

> I know I can use kroki.io or run my own Kroki. Is there a middle ground? Could the kroki.io images be downloaded into a local assets folder so we're only dependent on kroki.io at (documentation-)build time?

It should also be added in the documentation but you can use the attribute `kroki-fetch-diagram` to fetch the diagrams. Please note that currently there's a small issue. You will need to install an additional dependency:

```
npm install unxhr
```

**Comment by marcelstoer** [comment]
> It should also be added in the documentation

The HTML image src points to kroki.io and I see no local images.

> but you can use the attribute `kroki-fetch-diagram` to fetch the diagrams

Where would this have to be added? I don't see it mentioned anywhere here or in the Kroki manual.

**Comment by Mogztter** [comment]
> Never mind, I figured it out. For others: it's :kroki-fetch-diagram: inside your .adoc.
> Is there a way I could set :kroki-server-url: and/or :kroki-fetch-diagram: globally for Antora rather than repeat it on every affected .adoc page?

Yes, you add it in your playbook, see: https://docs.antora.org/antora/2.2/playbook/configure-asciidoc/

Is that working?

**Comment by marcelstoer** [comment]
Indeed, thanks. I just had to consider that this flag must obviously be a boolean. Hence, this becomes:

```yaml
asciidoc:
  attributes:
    kroki-fetch-diagram: true
  extensions:
    - asciidoctor-kroki
```

**Comment by Mogztter** [comment]
@marcelstoer Is everything working as expected with the above configuration? I'm asking so we know what to add in the documentation.

**Comment by marcelstoer** [comment]
Yes, all good, thanks.

**Comment by educaza007** [comment]
Hi
I'm using the Kroki extension in Antora and it works fine except for D2 diagrams. Has this happened to anyone else?

**Comment by Hollerweger** [comment]
Can't get it working for diagrams as files. Inline like above works fine but when i try to reference a file I get always `ENOENT: no such file or directory, open '07-test.puml' - plantuml::07-test.puml[]`
Where do I need to locate the diagrams? Does not work in image folder or in pages folder.
Tried with and without `kroki-fetch-diagram: true`
I'm using the antore Dockerimage for building:
```
FROM antora/antora:3.1.12
RUN yarn global add @antora/lunr-extension
RUN apk add ruby
RUN gem install asciidoctor-pdf
RUN yarn global add @antora/pdf-extension
RUN yarn global add asciidoctor-kroki
```

**Comment by ggrossetie** [comment]
@Hollerweger please don't comment on issues closed 5 years ago. If you have an usage question, please ask on https://chat.asciidoctor.org.

You can find example on how to use PlantUML in Antora in: https://github.com/asciidoctor/asciidoctor-kroki/tree/master/test/antora/docs/modules/ROOT

As far as I remember, we only support diagrams located in `examples`.
