### ISSUE TITLE
New JavaScript version

### ISSUE THREAD

**Issue by micwron** [Mogztter/asciidoctor-kroki#381]
Hi! 
It's been 8 months since the last JS-Release and there have been some useful changes (e.g. route logs through logger).
Could we please have a new version?

Thanks,
Michal

**Comment by Mogztter** [comment]
Hey Michal,

That's a good point.
Initially, my goal was to finish https://github.com/Mogztter/asciidoctor-kroki/pull/339 and include https://github.com/Mogztter/asciidoctor-kroki/issues/334 in the next release but we can postpone this two enhancements.

I will release a new version in the next few days.

Please note that we are using the issue tracker for verified bugs and enhancement requests only. In the future, please use the project chat at https://kroki.zulipchat.com/ for such request. Thanks!
