### ISSUE TITLE
Document configuration options

### ISSUE THREAD

**Issue by marcelstoer** [Mogztter/asciidoctor-kroki#39]
Bits and pieces I learned in discussions that should be documented:

**General diagram options**
> here: https://github.com/asciidoctor/asciidoctor-diagram
> we are trying to stay compatible with Asciidoctor diagram

> please note that diagram attributes are not supported since the Kroki API does not support specific attributes: https://github.com/asciidoctor/asciidoctor-diagram#diagram-attributes

**All Asciidoctor Kroki parameters**

Besides `kroki-server-url` and `kroki-fetch-diagram` there are probably others?

**Comment by Mogztter** [comment]
From https://github.com/eshepelyuk/asciidoctor-plantuml.js#overview

> This extension mimics the behavior of the Asciidoctor Diagram as closely as possible. Positional and named attributes as well as PNG and SVG formats are supported.

> .PlantUML example
> [plantuml#myId,mydiagram,svg,role=sequence] (1) (2) (3)
> ....
> alice -> bob
> ....
> (1) block style modifiers are supported
> (2) positional attributes are supported
> (3) named attributes are supported

**Comment by eshepelyuk** [comment]
@Mogztter you could easily re-implement this by copy pasting the code from my old extension, couldn't you ?
