### ISSUE TITLE
why not supporting all of kroki supported format?

### ISSUE THREAD

**Issue by DBuret** [Mogztter/asciidoctor-kroki#40]
Hi,

first, thank you for your work in the asciidoc community.

I have a maybe dumb question: why asciidoctor-kroki is not supporting all of kroki's supported formats?

I did a dirty test: in my vscode extension that uses asciidoctor-kroki, if I patch [asciidoctor-kroki.js line 16588](https://github.com/Mogztter/asciidoctor-kroki/blob/master/dist/browser/asciidoctor-kroki.js#L16588) by adding vega and vegalite, these 2 formats now work in the asciidoctor preview (tuned to use an onprem kroki)

Any reason to not activate these formats? known bug?

Again, thanks a lot for your asciidoctor work (gitlab support, kroki, browser extension, ...)

happy easter!

**Comment by Mogztter** [comment]
Hi @DBuret !

> first, thank you for your work in the asciidoc community.

:blush: 

> I have a maybe dumb question: why asciidoctor-kroki is not supporting all of kroki's supported formats?
> I did a dirty test: in my vscode extension that uses asciidoctor-kroki, if I patch asciidoctor-kroki.js line 16588 by adding vega and vegalite, these 2 formats now work in the asciidoctor preview (tuned to use an onprem kroki)
> Any reason to not activate these formats? known bug?

There's no dumb question :wink: 
Actually, I've added `vega` and `vegalite` in https://github.com/Mogztter/asciidoctor-kroki/commit/1b6e63f8b5643da677a38a862e65fc1ae906e87a and it should be available in the latest release 0.7.0: https://www.npmjs.com/package/asciidoctor-kroki

Are you using the latest version in your VSCode extension?
Please note that another community member is also working on a VSCode extension for Kroki: https://gitlab.com/akosma/kroki-vscode

> Again, thanks a lot for your asciidoctor work (gitlab support, kroki, browser extension, ...)
> happy easter!

Thanks for your kind words!
:rabbit: :rabbit: :rabbit:

**Comment by Mogztter** [comment]
@DBuret Can you please confirm that it's working with the latest version?

**Comment by Mogztter** [comment]
Closing this issue.
@DBuret Feel free to reopen if it's not working for you.
