### ISSUE TITLE
Create an Antora adapter to write diagrams to the output images directory

### ISSUE THREAD

**Issue by Mogztter** [Mogztter/asciidoctor-kroki#5]
Otherwise the diagrams won't be resolved.
Currently it's not possible to use the `kroki-fetch-diagram` feature in Antora.

**Comment by Mogztter** [comment]
resolved in 54cf7da44f373a2809070ee1775e567b062c217e

**Comment by akosma** [comment]
Can we now save diagrams locally in Antora websites? Yeah!

**Comment by akosma** [comment]
Is this documented somewhere? Is there something to configure to make it work?

**Comment by Mogztter** [comment]
> Is this documented somewhere? 

No but I heard it's working :sweat_smile: 

> Is there something to configure to make it work?

If you define `kroki-fetch-diagram` it should work.

**Comment by akosma** [comment]
It does work! However in our case (we use a custom built Docker image to drive builds both locally and on our CI/CD pipeline with the same config) we had to `yarn global add mkdirp unxhr` to make it work, but it did work!

**Comment by akosma** [comment]
For info, our Docker image builds `FROM antora/antora:2.2.0`

**Comment by akosma** [comment]
And I've just tried it together with asciidoctor-reveal.js, and it also works perfectly well.

**Comment by Mogztter** [comment]
> It does work! 

Cool 👍 
@akosma We should probably add a mention somewhere in the README. If you want to update the README I will gladly merge it 😉 

> However in our case (we use a custom built Docker image to drive builds both locally and on our CI/CD pipeline with the same config) we had to yarn global add mkdirp unxhr to make it work, but it did work!

I don't remember why I didn't add `unxhr` as a dependency... I will open an issue to track it.
