### ISSUE TITLE
Prefix auto-generated image filenames with diag-

### ISSUE THREAD

**Issue by danyill** [Mogztter/asciidoctor-kroki#63]
As pointed out in #48, asciidoctor-diagram prefixes auto-generated image filenames with `diag-`

I'd be keen to have the `diag-` prefix in asciidoctor-kroki as a way of namespacing the generated images which don't have an explicit filename (for instance useful if one wished to include in a `.gitignore`).

**Comment by Mogztter** [comment]
> I'd be keen to have the diag- prefix in asciidoctor-kroki as a way of namespacing the generated images which don't have an explicit filename (for instance useful if one wished to include in a .gitignore).

That's a very good point and it will get us one step closer to Asciidoctor diagram :+1:

**Comment by anb0s** [comment]
May be it would be also good to have it configured? E.g. `kroki-fetch-diagram-prefix` default set to `diag-` ? Only for auto-generated file-names... so i would set it to `generated-` or if possible `generated/` to have it in an imgdir subfolder.
