### ISSUE TITLE
'npm run lint' failed @ windows

### ISSUE THREAD

**Issue by anb0s** [Mogztter/asciidoctor-kroki#67]
I've tried the [Contributing](https://github.com/Mogztter/asciidoctor-kroki#contributing) description @ Windows 10 with fresh clone and versions:
- npm@6.14.4
- node@v12.16.3

`npm -i` --> Works
`npm run lint` returns error:

```
> asciidoctor-kroki@0.8.2 lint C:\Users\user\dev\asciidoctor-kroki
> standard src/**.js test/**.js

Der Befehl "standard" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! asciidoctor-kroki@0.8.2 lint: `standard src/**.js test/**.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the asciidoctor-kroki@0.8.2 lint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

The german text says` the command "standard" is wrong or cannot be found`.

**Comment by anb0s** [comment]
After `npm i standard` now it runs without error:

```
$ npm run lint

> asciidoctor-kroki@0.8.2 lint C:\Users\user\dev\asciidoctor-kroki
> standard src/**.js test/**.js
```

**Comment by anb0s** [comment]
The `devDependencies `have already `"standard": "^14.3.3"` and it should work !
It looks like again something different happenes @ windows...

**Comment by Mogztter** [comment]
The command is `npm i` not `npm -i`. You can also use the long form `npm install`. Not sure if it's a typo or not but that can explain why the dependencies were not installed.

**Comment by anb0s** [comment]
I've started with fresh repo `git clean -dfx` and now it looks good :)

- [x] npm -i
- [x] npm run lint
- [ ] npm run test --> failed, see #68

**Comment by anb0s** [comment]
@Mogztter thx, it was a typo i use `npm i` or `npm install`

Now it just works :)
