### ISSUE TITLE
Document the macro form

### ISSUE THREAD

**Issue by danyill** [Mogztter/asciidoctor-kroki#72]
Currently we don't document the macro form for use with asciidoctor-kroki and initially I thought it wasn't supported based on the README. 

Looking through the tests I joyfully realise it is indeed possible!

```asciidoc
plantuml::${file}[svg,role=sequence]
vegalite::test/fixtures/chart.vlite[svg,role=chart]
bytefield::test/fixtures/simple.bytefield[svg,role=bytefield,opts=inline]
vegalite::test/fixtures/chart.vlite[svg,role=chart,opts=interactive]
```

I'll do a PR for this at some stage.

**Comment by Mogztter** [comment]
https://blog.codinghorror.com/if-it-isnt-documented-it-doesnt-exist/ :sweat_smile: 

> I'll do a PR for this at some stage.

That would be great :grinning:

**Comment by juracy** [comment]
I think the macro form is already in README.md

By the way, why not README.adoc ?

**Comment by Mogztter** [comment]
> I think the macro form is already in README.md

You're right, I will close this issue.

> By the way, why not README.adoc 

The main reason is that npmjs only supports Markdown: https://www.npmjs.com/package/asciidoctor-kroki
It's sad but what can we do... 😞
