### ISSUE TITLE
[proposal] Add a sample project to bootstrap antora integration.

### ISSUE THREAD

**Issue by eshepelyuk** [Mogztter/asciidoctor-kroki#73]
It may be easier to users to startup with antora + kroki by cloning sample repository.
Similar to one existed for my deprecated `ascidoctor-plantuml` extension.

I am ready to create a new repo for this and contribute it together with documentation updates.

**Comment by Mogztter** [comment]
Sure that sounds like a good idea. I can add a link to your repository in the README.
Another idea would be to add Antora with Kroki enabled in this repository to document this extension?

**Comment by djencks** [comment]
I have an example project at https://gitlab.com/djencks/simple-examples under extensions/kroki-extension.  Since the current (0.9.1) version doesn't work with Antora, I'll update it to work with 0.8.2 as a fixed version.

**Comment by Mogztter** [comment]
I've copied/pasted David's example project in: https://github.com/Mogztter/asciidoctor-kroki/pull/108.
We can use it to write integration tests.
