### ISSUE TITLE
Errors, warnings and failures in browser example

### ISSUE THREAD

**Issue by danyill** [Mogztter/asciidoctor-kroki#81]
(I start by confessing I know little about browserify or javascript in browsers in general)

When I try to use the macro form from a browser as per the README:

```html
<html>
  <head>
    <script src="node_modules/@asciidoctor/core/dist/browser/asciidoctor.js"></script>
    <script src="node_modules/asciidoctor-kroki/dist/browser/asciidoctor-kroki.js"></script>
  </head>
  <body>
    <div id="content"></div>
    <script>
      var input = 'plantuml::hello.puml[svg,role=sequence]'

      var asciidoctor = Asciidoctor()
      var kroki = AsciidoctorKroki

      const registry = asciidoctor.Extensions.create()
      kroki.register(registry)
      var result = asciidoctor.convert(input, {'extension_registry': registry})
      document.getElementById('content').innerHTML = result
    </script>
  </body>
</html>
```
I receive the following error in the browser window:

```
fs.readFileSync is not a function - plantuml::hello.puml[]
```

I think `readFileSync` does not exist because it is specifically excluded (quite likely for good reasons, but then the wrong example to choose maybe?)

https://github.com/Mogztter/asciidoctor-kroki/blob/982d016dd89d811d88fa1b73ec40bb40020a3e89/package.json#L17

I removed the exclude for node-fs which allowed processing to continue but then I received an asciidoctor.js warning suggesting I had sinned by not specifying an absolute path.

Fair enough, but `plantuml::hello.puml[]` doesn't work and neither does `plantuml::file:///home/mulhollandd/Documents/test-kroki/hello.puml[svg,role=sequence]`.

In my console window, I have the following error message:

```
SecurityError: Jail is not an absolute path: . asciidoctor.js:413:20
    Error self-hosted:891
    constructor file:///home/mulhollandd/Documents/test-kroki/node_modules/@asciidoctor/core/dist/browser/asciidoctor.js:413
    $Exception_new$1 file:///home/mulhollandd/Documents/test-kroki/node_modules/@asciidoctor/core/dist/browser/asciidoctor.js:4939
    send file:///home/mulhollandd/Documents/test-kroki/node_modules/@asciidoctor/core/dist/browser/asciidoctor.js:1674
    $$exception file:///home/mulhollandd/Documents/test-kroki/node_modules/@asciidoctor/core/dist/browser/asciidoctor.js:4965
    $$raise file:///home/mulhollandd/Documents/test-kroki/node_modules/@asciidoctor/core/dist/browser/asciidoctor.js:4653
    $$system_path file:///home/mulhollandd/Documents/test-kroki/node_modules/@asciidoctor/core/dist/browser/asciidoctor.js:32604
    $$normalize_system_path file:///home/mulhollandd/Documents/test-kroki/node_modules/@asciidoctor/core/dist/browser/asciidoctor.js:25244
    normalizeSystemPath file:///home/mulhollandd/Documents/test-kroki/node_modules/@asciidoctor/core/dist/browser/asciidoctor.js:42403
    diagramBlockMacro file:///home/mulhollandd/Documents/test-kroki/node_modules/asciidoctor-kroki/dist/browser/asciidoctor-kroki.js:18981
    apply file:///home/mulhollandd/Documents/test-kroki/node_modules/@asciidoctor/core/dist/browser/asciidoctor.js:45476
    $$instance_exec file:///home/mulhollandd/Documents/test-kroki/node_modules/@asciidoctor/core/dist/browser/asciidoctor.js:3818
    send file:///home/mulhollandd/Documents/test-kroki/node_modules/@asciidoctor/core/dist/browser/asciidoctor.js:1674
    $$19 file:///home/mulhollandd/Documents/test-kroki/node_modules/@asciidoctor/core/dist/browser/asciidoctor.js:39343
    send file:///home/mulhollandd/Documents/test-kroki/node_modules/@asciidoctor/core/dist/browser/asciidoctor.js:1674
    $$process file:///home/mulhollandd/Documents/test-kroki/node_modules/@asciidoctor/core/dist/browser/asciidoctor.js:39347
    $$call file:///home/mulhollandd/Documents/test-kroki/node_modules/@asciidoctor/core/dist/browser/asciidoctor.js:17847
    send file:///home/mulhollandd/Documents/test-kroki/node_modules/@asciidoctor/core/dist/browser/asciidoctor.js:1674
    alias file:///home/mulhollandd/Documents/test-kroki/node_modules/@asciidoctor/core/dist/browser/asciidoctor.js:1864
    $$next_block file:///home/mulhollandd/Documents/test-kroki/node_modules/@asciidoctor/core/dist/browser/asciidoctor.js:29760
    $$next_section file:///home/mulhollandd/Documents/test-kroki/node_modules/@asciidoctor/core/dist/browser/asciidoctor.js:29476
    $$parse file:///home/mulhollandd/Documents/test-kroki/node_modules/@asciidoctor/core/dist/browser/asciidoctor.js:29134
    $$parse file:///home/mulhollandd/Documents/test-kroki/node_modules/@asciidoctor/core/dist/browser/asciidoctor.js:27594
    doc file:///home/mulhollandd/Documents/test-kroki/node_modules/@asciidoctor/core/dist/browser/asciidoctor.js:35875
    $$load file:///home/mulhollandd/Documents/test-kroki/node_modules/@asciidoctor/core/dist/browser/asciidoctor.js:35876
    $$convert file:///home/mulhollandd/Documents/test-kroki/node_modules/@asciidoctor/core/dist/browser/asciidoctor.js:36016
    convert file:///home/mulhollandd/Documents/test-kroki/node_modules/@asciidoctor/core/dist/browser/asciidoctor.js:41454
    <anonymous> file:///home/mulhollandd/Documents/test-kroki/test1.html:36

```

I may be going down a rabbit hole but I expect it to be an  educational rabbit hole.

Also while I'm there, should our html be just a little more correct to avoid browser warnings?

```html
<!DOCTYPE html>
  <head>
    <meta charset="utf-8">
```

I think for the example to work it should be more an inline diagram at the moment.

**Comment by danyill** [comment]
We solve the Jail error by setting safe to `unsafe` in our Asciidoctor options but now we've run full circle and we receive 

```
fs.readFileSync is not a function - plantuml::file:///home/mulhollandd/Documents/test-kroki/hello.puml[]
```

I shall Investigate :detective:!

**Comment by danyill** [comment]
Hmmm... perhaps this can never work because that's not the way JavaScript sandboxing is intended to work? Perhaps it can only work with http/https and I guess we need to have something in our options about reading from URIs?

Working on the WIP `issue-74-macro-path` and commenting out my (one line but still incorrect change) as well as removing the exclusion of node-fs.

```
// target = parent.getDocument().normalizeSystemPath(target)
```

We create a Gist and take the raw link from it and try:
```asciidoc

plantuml::https://gist.githubusercontent.com/danyill/224f132793ff68c0d21c4652f9feb107/raw/5e6f3f709ff867935c59c0f08eda93ffc9a5bbeb/test.puml[svg,role=sequence]
```

And receive for our trouble:

```
GET https://gist.githubusercontent.com/danyill/224f132793ff68c0d21c4652f9feb107/raw/5e6f3f709ff867935c59c0f08eda93ffc9a5bbeb/test.puml - error; reason: Url.URL is not a constructor - plantuml::https://gist.githubusercontent.com/danyill/224f132793ff68c0d21c4652f9feb107
```

We have modified our document so it now reads:

```html
<!DOCTYPE html>
  <head>
    <meta charset="utf-8">
    <script src="node_modules/@asciidoctor/core/dist/browser/asciidoctor.js"></script>
    <script src="node_modules/asciidoctor-kroki/dist/browser/asciidoctor-kroki.js"></script>
  </head>
  <body>
    <div id="content"></div>
    <script>
      var input = `
      
// plantuml::hello.puml[svg,role=sequence]

plantuml::https://gist.githubusercontent.com/danyill/224f132793ff68c0d21c4652f9feb107/raw/5e6f3f709ff867935c59c0f08eda93ffc9a5bbeb/test.puml[svg,role=sequence]

:twit: asdf
{test}
{twit}
[plantuml,alice-bob,svg,role=sequence]
....
alice -> bob
....

[graphviz]
....
digraph foo {
  node [style=rounded]
  node1 [shape=box]
  node2 [fillcolor=yellow, style="rounded,filled", shape=diamond]
  node3 [shape=record, label="{ a | b | c }"]

  node1 -> node2 -> node3
}
....
`
      var asciidoctor = Asciidoctor()
      var kroki = AsciidoctorKroki

      const registry = asciidoctor.Extensions.create()
      kroki.register(registry)
      var result = asciidoctor.convert(input, {'extension_registry': registry, safe: 'unsafe', attributes: {'allow-uri-read': true, 'test': 'hi'}})
      document.getElementById('content').innerHTML = result
    </script>
  </body>
</html>
```
:confused: :confused:

**Comment by danyill** [comment]
Some of the problem seems to originate from a recent change which replaced `URL.parse` with `Url.URL` which my browser cannot digest:

https://github.com/Mogztter/asciidoctor-kroki/commit/7e67a61fdbc9203a6a7ec4ef01a5cb6130594004#diff-dadaf90000d253c929d3941e09d9815aR16546

The previous version appears to work but `Url.URL` does not exist...

```diff
-    const url = Url.parse(settings.url)
+    const url = new Url.URL(settings.url)
```

That's also where we `node-fs` was excluded:

https://github.com/Mogztter/asciidoctor-kroki/commit/7e67a61fdbc9203a6a7ec4ef01a5cb6130594004#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R17

I fear these problems go beyond my meagre abilities for the time being and I must wait for Yuzi-Yoda to help me :grinning: 
It may be that this is WIP and I am just creating noise by getting in the way of a great work.

**Comment by Mogztter** [comment]
Nice investigation :detective: 
In a browser environment, we cannot and should not use the `node-fs` because it relies on the `fs` Node module. Browserify can in theory provide a "polyfill" but in practice that does not work very well with Asciidoctor.js.
That's the reason why we exclude `node-fs`.

The example in the documentation is incomplete and we should probably not use the macro in the browser because it requires additional configuration.
Here's what I'm using in the browser extension: https://github.com/asciidoctor/asciidoctor-browser-extension/blob/master/app/js/converter.js#L220-L243

As you can see, I provide my own VFS to take into account the restrictions of running in a Web Extension inside the browser.
I'm not sure if we should provide this implementation out-of-the-box because it highly depends on the environment. For instance, you could be running in the browser but using [IndexedDB](https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API) or the new [Native File System API](https://web.dev/native-file-system/] from Google/Chrome.

**Comment by danyill** [comment]
I think this is redundant with the new README. Thanks @Mogztter
