### ISSUE TITLE
Create more similar HTML compared to asciidoctor-diagram (alt attribute of img element)

### ISSUE THREAD

**Issue by stenzengel** [Mogztter/asciidoctor-kroki#98]
Split of #13 to simplify tracking. The sample Asciidoctor input and the generated HTML output of asciidoctor-diagram and asciidoctor-kroki can be found there. 

This issue only considers differences in the "alt" attribute:
asciidoctor-diagram replaces the "-" character in "my-filename" with " " in the "alt" attribute. Kroki does no replace this character.

**Comment by Mogztter** [comment]
It should be an easy fix if someone wants to give it a try. The corresponding code is: 

https://github.com/Mogztter/asciidoctor-kroki/blob/ed320a5b10c619fcd2e2ad5dc397c011892f67ff/src/asciidoctor-kroki.js#L89-L96

So if `attrs.target` is defined, we should do `alt = attrs.target.replace(/-/g, ' ')`.
